[package]
name = "ebpf-common"
version = "0.1.0"
edition.workspace = true

[dependencies]
ebpf-memory-monitor-common = { path = "../ebpf-memory-monitor-common" }
aya-ebpf = { workspace = true }

[lib]
path = "src/lib.rs"
